Creating Repayments calculator with form block
hlxsites/nedbank pull request #48
Opened 2023-02-07 14:18 UTC by vdua

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--<repo>--<owner>.hlx.page/
- After: https://<branch>--<repo>--<owner>.hlx.page/

2023-02-07 14:21 UTC, vdua commented
Pending changes:
1. layout as per nedbank's requirement (field styling is present as per the original styling)
2. Integrating formula and fragments.

2023-02-09 08:17 UTC, sdmcraft requested changes

2023-02-09 08:17 UTC, sdmcraft commented on blocks/form/form.css
> +.field-wrapper {
Few comments on css:

1. Please consider using `less` which is being used for defining styles elsewhere in this repo.
2. Consider using global style tokens (colors, fonts etc.) defined in https://github.com/hlxsites/nedbank/blob/1c79a83851b5f99c495a8e247a84e969c8e69974/styles/styles.less
3.  https://form2--nedbank--hlxsites.hlx.page/en/personal/borrow/personal-loans-form opens up the calculator in a single column which is different from the reference site. We'd need to align to its styling.

2023-02-09 08:17 UTC, sdmcraft commented on blocks/form/form.js
> +async function submitForm(form) {
Do we need this? I think the calculator form submits nothing to the server.

2023-02-09 16:55 UTC, vdua commented on blocks/form/form.css
> +.field-wrapper {
@sdmcraft Resolved the issues.

2023-02-13 07:41 UTC, vdua commented on blocks/form/form.css
> +.field-wrapper {
@sdmcraft I think we should put a message here which says auto-generated file

2023-02-13 11:10 UTC, tripodsan commented on blocks/form/form.js
> +  }
```suggestion
  let arrayInputs = inputs;
  if (!(inputs instanceof Array)) {
    arrayInputs = [inputs];
  }
  const arrayInputs = Array.isArray(inputs) ? inputs : [inputs];
```

2023-02-13 11:12 UTC, tripodsan commented on blocks/form/form.js
> +  return import('./formatting.js').then(formatFn, errorFn);
I think the import can be global, as it doesn't seem to be large. but this is a bit a confusing call.
or:

```suggestion
  const formatNumber = import('./formatting.js');
  return formatNumber.then(formatFn, errorFn);
```

2023-02-13 11:17 UTC, tripodsan commented on blocks/form/form.js
> +  return import('./formatting.js').then(formatFn, errorFn);
some comment would be useful here.... however, I don't think this is correct all the time. you relying on the fact that that `import` is always async, which it might not be, if the module is already loaded.

maybe something like:

```suggestion
  const formatNumber = await import('./formatting.js');
  return new Promise((resolve) => setImmediate(() => formatNumber());
```

2023-02-13 12:15 UTC, trieloff commented on blocks/form/form.js
> +  return import('./formatting.js').then(formatFn, errorFn);
@tripodsan `import()` returns a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#return_value), so the `.then()` call should work, even if we are dealing with a promise that is resolved immediately.

2023-02-13 14:21 UTC, trieloff commented
Some content-modelling feedback first:

```jsonc
        {
            "Description": "",
            "Display Format": "currency/ZAR", // I'm wondering if we can make this a CSS property, so that authors do not have to worry
            "Group": "",
            "Hidden": "",
            "Hidden Expression": "",
            "Label": "How much you’ll pay back each month",
            "Label Expression": "", // Do we need this? If not, let's drop it from the model
            "Mandatory": "",
            "Max": "",
            "Min": "",
            "Name": "emi",
            "Selected": "", // Isn't this the same as "Value", just for checkboxes and radio buttons?
            "Step": "",
            "Tooltip": "This estimate covers all fees, the loan instalment, the interest charged for the month and your insurance, if you’ve included the monthly premium.", // in HTML, this is `title` – not sure if we want to keep it separate
            "Type": "output", // I'm thinking of combining `Type` and the remainder of `Display Format`, see below
            "Value": "197.93",
            "Value Expression": "=ROUND(IF(D6, D18, 0) +'helix-constants'!C11 + (D13*100 / 'helix-constants'!C10 * (D17+ D13*100 / 'helix-constants'!C10* D17 + 'helix-constants'!C11) / (1 - POWER(1 +D13*100 / 'helix-constants'!C10, -1 * (12 *D4)))),2)"
        },
```

My alternative would look like this:
```jsonc
        {
            "Description": "",
            "Group": "",
            "Display": "output", // this could also be `hidden`, `disabled`, or `input` (default)
            "Display Expression": "",
            "Label": "How much you’ll pay back each month",
            "Mandatory": "",
            "Max": "",
            "Min": "",
            "Name": "emi",
            "Step": "",
            "Title": "This estimate covers all fees, the loan instalment, the interest charged for the month and your insurance, if you’ve included the monthly premium.",
            "Type": "currency",
            "Value": "197.93",
            "Value Expression": "=ROUND(IF(D6, D18, 0) +'helix-constants'!C11 + (D13*100 / 'helix-constants'!C10 * (D17+ D13*100 / 'helix-constants'!C10* D17 + 'helix-constants'!C11) / (1 - POWER(1 +D13*100 / 'helix-constants'!C10, -1 * (12 *D4)))),2)"
        },
```

In terms of type, we would have the HTML standards:
- checkbox
- color
- date
- datetime-local
- email
- month
- number
- password (not yet supported, needs more stuff)
- radio
- range
- tel
- text
- time
- url
- week

Plus some non-standards
- currency
- unit-*
- country
- address

We can probably use CSS Variables to express the Display Format preferences:

```css
output[type="currency"] {
  --form-currency: "ZAR";
  --form-currency-display: "narrowSymbol";
  --form-maximum-significant-digits: 2;
}
```

We'd then `getComputedStyle(element).getPropertyValue('--form-currency');` to get the value for formatting.

2023-02-15 06:29 UTC, sdmcraft commented on blocks/form/form.css
> +.field-wrapper {
You could add these 2 lines to the  `less`  file 
```
+@plugin '../../less-scripts/autogen-comment-plugin';
+autocomment();
```

Then whenever you do `npm run lessc`,  it'll auto-add a comment like this to the generated `css` file 
```
+/*!
+ * This is a autogenerated file. Please don't change the content directly.
+ * To change the css, change the same named .less file.
+ * After changing .less file, run 'npm run lessc' from terminal to autogenerate .css file.
+ */
```

Let me also add this info to the repository's README.

2023-02-16 20:01 UTC, vdua commented on blocks/form/form.js
> +  return import('./formatting.js').then(formatFn, errorFn);
I discussed with customer. They do not need the full Intl support and have the following requirements

1. grouping symbol and decimal symbol will always be `,`  and `.` 
2. The currency symbol will change once they move to other south african countries and there will be only limited number of countries they think.
3. They do not need to format `years` and `months` in different language.

I already found a formatting function which performs almost equivalent of Intl (except the initial lag) [1] given the set of constraints the customer has

[1] https://jsfiddle.net/vdua/mpodxt4e/1/

2023-02-17 04:29 UTC, vdua commented
> ```Display": "output", // this could also be `hidden`, `disabled`, or `input` (default)```

Hidden has two meanings right now : The current state of the field (display css property of the field) and whether that field is being used as a constant (<input type=hidden/>). That information needs to be captured to generate the HTML structure. We can create a widget for all the constants as well, but that will not be optimal. The other way could be to create the element when it needs to be displayed (but we may not be able to do that if there is some custom logic involved)

We would need something for the constants so that we do not bloat the dom. 

If there is no Dispaly Expression, then treat it as hidden inputs (but places where formulas are not being used to change the display dynamically, it could be a problem)
Also disabled has a different meaning in html where it doesn't allow data to be submitted as well for that particular field. A hidden field can be disabled as well. 

But that is something not a concern right now and can work for nedbank. 
Though the original form block logic that renders the forms would have this condition which I do not want. I want rules to be added in the form block as an extension point (I have done that and will raise a PR), if someone doesn't want the excel rules, they can use JS as they by just removing 1 line of code. 

> ```We can probably use CSS Variables to express the Display Format preferences:```

That would work. 

> Plus some non-standards
* currency
* unit-*
* country
* address

+1 for currency and country.

For unit-*, if I understood correctly, it will be a number field with the format applied accordingly. And can be decorated via custom code. In the case of nedbank unit-year and unit-% would be created as a number field and they would be using a slider in their custom extensions

In all the forms that I have filled or seen address is something that is not a standard anywhere. I would keep it out right now. It can work potentially by creating a fieldset in the form block and letting the extension points add fields to it as per the requirements of the customer, but I don't see any value in it right now.

> In terms of type, we would have the HTML standards:

I would like to add fieldset to that as well.

2023-02-17 11:21 UTC, sdmcraft commented on blocks/form/form_variables.less
> +@font-family-opensans-regular: "Open Sans Regular";
I'd suggest using the style tokens from the the common location here as that's make the managment much easier. https://github.com/hlxsites/nedbank/blob/2f0d7272eacccd82be3dd4e80904d332064d8606/styles/variables.less#L53-L56 

If you need block level overrides, you can define you own tokens which reuse the global tokens. Something like 
```
@font-family-forms-bold: @font-family-nedbank-bold;
```

2023-02-24 06:28 UTC, vdua commented
Closing this PR. Will be raising a new one after incorporating the suggestions at https://github.com/vdua/nedbank/pulls

2023-02-24 06:28 UTC, closed without merging