Add repeatable fieldset support
hlxsites/nedbank pull request #69
Opened 2023-02-23 06:45 UTC by Pareesh

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--<repo>--<owner>.hlx.page/
- After: https://<branch>--<repo>--<owner>.hlx.page/

2023-02-24 06:42 UTC, vdua requested changes
* fix different markup for button here than elsewhere in the form
* id generation logic should be same
* name of the field should be same so that you can get array of elements when you are doing operations on that paricular field
* templating logic can be simplified

2023-02-24 06:42 UTC, vdua commented on blocks/form/decorators/fieldsets.js
> +      if (fieldsetEl.hasAttribute('repeatable')) {
can we have the template as `fieldsetEl.outerHTML` ?

2023-02-24 06:42 UTC, vdua commented on blocks/form/decorators/fieldsets.js
> +  return button;
the markup of this button is different than the button we create in the form block ? Can we fix that

2023-02-24 06:42 UTC, vdua commented on blocks/form/decorators/fieldsets.js
> +  return button;
I think in the case of repeatable fieldset, the form block should add two buttons add/remove on its own.

2023-02-24 06:42 UTC, vdua commented on blocks/form/decorators/fieldsets.js
> +        .filter((c) => ['INPUT', 'SELECT', 'TEXTAREA', 'FIELDSET'].includes(c.tagName)).forEach((el) => {
tolowercase

2023-02-24 06:44 UTC, vdua commented on blocks/form/decorators/fieldsets.js
> +  legend.childNodes[0].data = legend.dataset.textTemplate.replace('#', i + 1);
I was thinking of doing it via css counters.

2023-03-03 07:02 UTC, Pareesh commented on blocks/form/decorators/fieldsets.js
> +  return button;
Hi @vdua ,
For Nedbank case, a single Add button is shown for whole repeatable fieldset and one remove button for fieldsetitem. I have kept the implementation to satisfy this case. In future maybe we can append code for Add button per fieldset item.

2023-03-05 18:01 UTC, Pareesh commented on blocks/form/decorators/repayments-calculator.js
> +  extraCashFieldSet: ['extraCashHeading', 'extraCash'].map(getSelector),
yes

2023-03-05 18:08 UTC, Pareesh commented on blocks/form/decorators/fieldsets.js
> +      legend.childNodes[0].data = legend.dataset.textTemplate.replace('#', index + 1);
Implement using css counters

2023-03-20 09:13 UTC, closed without merging